services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=''
      - MYSQL_DATABASE=todo
      - MYSQL_USER=root
      - MYSQL_PASSWORD=''
    volumes:
      - ./mysql_data:/var/lib/mysql